"""The lockfile sweep drops every CUDA pin with its comment block, and nothing else.

The images install torch's CPU build from PyTorch's index before their pinned requirements, so a
pin of torch's CUDA companions only drags the CUDA runtime in (the proxy image carried 1.7 GB of
it). Newer torch reaches it through cuda-toolkit and cuda-bindings rather than nvidia-* pins, and
the old `sed /^nvidia-/d` also left each dropped pin's "# via" lines under the package before
it. scripts/drop-cuda-pins.awk drops nvidia-* and cuda-* pins with their blocks, and the
orphaned blocks an earlier sweep left; scripts/compile-requirements.sh runs it on every lockfile
it writes.
"""
import os
import re
import shutil
import subprocess
from pathlib import Path

import pytest

_ROOT = Path(__file__).resolve().parents[3]
AWK = _ROOT / "scripts" / "drop-cuda-pins.awk"


def _bash():
    if os.name == "nt":
        git = shutil.which("git")
        if git:
            candidate = Path(git).resolve().parents[1] / "bin" / "bash.exe"
            if candidate.exists():
                return str(candidate)
    return shutil.which("bash")


pytestmark = pytest.mark.skipif(_bash() is None, reason="needs bash and awk")

LOCKFILE = """\
#
# This file is autogenerated by pip-compile with Python 3.11
#
cuda-bindings==13.4.3
    # via torch
cuda-pathfinder==1.8.3
    # via cuda-bindings
cuda-toolkit[cublas,cudart]==13.0.3.0
    # via torch
fastapi==0.142.2
    # via -r requirements.in
numpy==2.4.6
    # via
    #   accelerate
    #   transformers
    # via
    #   cuda-toolkit
    #   nvidia-cudnn-cu13
nvidia-cublas==13.1.1.3
    # via
    #   cuda-toolkit
    #   nvidia-cudnn-cu13
sympy==1.14.0
    # via torch

# The following packages are considered to be unsafe in a requirements file:
# torch
"""

EXPECTED = """\
#
# This file is autogenerated by pip-compile with Python 3.11
#
fastapi==0.142.2
    # via -r requirements.in
numpy==2.4.6
    # via
    #   accelerate
    #   transformers
sympy==1.14.0
    # via torch

# The following packages are considered to be unsafe in a requirements file:
# torch
"""


def test_cuda_pins_go_with_their_blocks_and_nothing_else_changes(tmp_path):
    lockfile = tmp_path / "requirements.txt"
    lockfile.write_text(LOCKFILE, encoding="utf-8", newline="\n")
    r = subprocess.run([_bash(), "-c", f'awk -f "{AWK.as_posix()}" "{lockfile.as_posix()}"'],
                       capture_output=True, encoding="utf-8", timeout=30)
    assert r.returncode == 0, r.stderr
    assert r.stdout == EXPECTED


def test_a_swept_lockfile_is_left_as_it_is(tmp_path):
    lockfile = tmp_path / "requirements.txt"
    lockfile.write_text(EXPECTED, encoding="utf-8", newline="\n")
    r = subprocess.run([_bash(), "-c", f'awk -f "{AWK.as_posix()}" "{lockfile.as_posix()}"'],
                       capture_output=True, encoding="utf-8", timeout=30)
    assert r.stdout == EXPECTED


def test_the_compile_script_sweeps_every_lockfile_that_installs_torch():
    script = (_ROOT / "scripts" / "compile-requirements.sh").read_text(encoding="utf-8")
    assert "/^nvidia-/d" not in script                      # the old sweep, which missed cuda-*
    assert script.count("sweep requirements.txt") == 2      # the proxy's, and each image's in the loop
    assert re.search(r'awk -f /w/scripts/drop-cuda-pins\.awk', script)
