import hashlib
import json
import logging
import os
from typing import Optional, Tuple

logger = logging.getLogger(__name__)

_GCP_PROJECT = os.getenv("GCP_PROJECT_ID", "")
_PROXY_KEYS_SECRET = os.getenv("PROXY_KEYS_SECRET_NAME", "token-proxy-api-keys")
_LOCAL_PROXY_KEYS_FILE = os.getenv("LOCAL_PROXY_KEYS_FILE", "")

# In-process cache — refreshed on each validate call after TTL (simple approach)
_KEY_CACHE: dict = {}
_CACHE_TTL_SECONDS = int(os.getenv("KEY_CACHE_TTL_SECONDS", "300"))
import time
_CACHE_LOADED_AT: float = 0.0


def _fetch_secret(secret_name: str) -> Optional[str]:
    try:
        from google.cloud import secretmanager

        client = secretmanager.SecretManagerServiceClient()
        name = f"projects/{_GCP_PROJECT}/secrets/{secret_name}/versions/latest"
        response = client.access_secret_version(request={"name": name})
        return response.payload.data.decode("UTF-8")
    except Exception as exc:
        logger.error("Secret Manager fetch failed [%s]: %s", secret_name, exc)
        return None


def _load_key_cache() -> None:
    global _KEY_CACHE, _CACHE_LOADED_AT

    # Local dev: read keys from a local JSON file (generated by
    # scripts/local/deploy-local.sh) instead of Secret Manager.
    # STORAGE_BACKEND=local forces file-based auth even if LOCAL_PROXY_KEYS_FILE is unset.
    storage_backend = os.getenv("STORAGE_BACKEND", "gcs").lower().strip()
    if _LOCAL_PROXY_KEYS_FILE or storage_backend == "local":
        try:
            with open(_LOCAL_PROXY_KEYS_FILE, "r", encoding="utf-8") as f:
                _KEY_CACHE = json.load(f)
            _CACHE_LOADED_AT = time.monotonic()
        except FileNotFoundError:
            logger.warning("Local proxy keys file not found: %s", _LOCAL_PROXY_KEYS_FILE)
        except json.JSONDecodeError as exc:
            logger.error("Invalid local proxy keys JSON [%s]: %s", _LOCAL_PROXY_KEYS_FILE, exc)
        return

    raw = _fetch_secret(_PROXY_KEYS_SECRET)
    if raw:
        try:
            _KEY_CACHE = json.loads(raw)
            _CACHE_LOADED_AT = time.monotonic()
        except json.JSONDecodeError as exc:
            logger.error("Invalid proxy keys JSON: %s", exc)


def validate_proxy_key(api_key: str) -> Tuple[bool, Optional[str], Optional[dict]]:
    """
    Validate a developer proxy API key.

    Returns (is_valid, user_id_or_tenant_id, tenant_metadata).

    The secret in Secret Manager (or local-keys.json) is JSON with two supported formats:
        Legacy: { "<sha256_of_key>": "<user_id>", ... }
        New:    { "<sha256_of_key>": {"tenant_id": "...", "tier": "..."}, ... }

    For new format, returns (True, tenant_id, metadata_dict).
    For legacy format, returns (True, user_id, None).

    Proxy admins add keys via gcp-deploy.sh / admin CLI.
    Developers never see LLM provider keys — only their proxy key.
    """
    global _CACHE_LOADED_AT
    now = time.monotonic()
    if not _KEY_CACHE or (now - _CACHE_LOADED_AT) > _CACHE_TTL_SECONDS:
        _load_key_cache()

    key_hash = hashlib.sha256(api_key.encode("utf-8")).hexdigest()
    entry = _KEY_CACHE.get(key_hash)
    
    if entry is None:
        return False, None, None
    
    # Support both legacy string format and new object format
    if isinstance(entry, dict):
        # New format: {tenant_id, tier, created}
        tenant_id = entry.get("tenant_id", "default")
        return True, tenant_id, entry
    else:
        # Legacy format: entry is a user_id string
        return True, entry, None


def is_admin_key(metadata: Optional[dict]) -> bool:
    """Return True when a validated key's metadata grants the admin/impersonation
    scope.

    Admin keys may (a) assume another tenant via the ``X-Tenant-ID`` header
    (cross-tenant impersonation), (b) name an arbitrary RAG collection via
    ``x_rag_collection``, and (c) call the cross-tenant admin/GDPR endpoints.
    Legacy string-format keys (metadata is None) are never admin.
    """
    return bool(isinstance(metadata, dict) and metadata.get("admin"))


def is_suspended(metadata: Optional[dict]) -> bool:
    """Return True when a validated key is flagged suspended in its metadata.

    Suspension is set out-of-band by the key-store lifecycle (management console /
    ``issue-key.sh``); this proxy only *enforces* it — a suspended key authenticates
    to a known tenant but is rejected (HTTP 403) at ``_authenticate``. Legacy
    string-format keys (metadata is None) can never be suspended.
    """
    return bool(isinstance(metadata, dict) and metadata.get("suspended"))


def get_tenant_for_key(api_key: str) -> Optional[dict]:
    """
    Get tenant metadata for a validated API key.
    
    Returns the metadata dict if the key is in new format, None otherwise.
    Used by tenancy resolver to build TenantContext.
    """
    key_hash = hashlib.sha256(api_key.encode("utf-8")).hexdigest()
    entry = _KEY_CACHE.get(key_hash)
    
    if isinstance(entry, dict):
        return entry
    return None


def get_llm_provider_key(provider: str) -> Optional[str]:
    """
    Fetch the LLM provider API key from Secret Manager.
    Called only by the proxy — developers never receive this value.
    """
    env_var = f"SECRET_{provider.upper().replace('-', '_')}_API_KEY"
    secret_name = os.getenv(env_var, f"llm-key-{provider.lower()}")
    value = os.getenv(f"LLM_KEY_{provider.upper()}")  # local dev override
    if value:
        return value
    return _fetch_secret(secret_name)
