"""
G24 — Adaptive Bypass

Dynamically skips specific G-groups for request patterns that historically
show negative savings (token increase). Rules are loaded from
config/adaptive_bypass_rules.yaml, generated by the Phase 4 analysis pipeline.

The middleware runs early in the pipeline (after G0 rate limit, before G4).
When a request matches a bypass rule, the target G-group is added to
ctx.skip_groups so downstream pipeline stages can skip it.

Reference: Phase 4 in multi-tenant-validation-plan.md
"""

import logging
import os
from pathlib import Path
from typing import Any, Dict, List, Optional

import yaml

from middleware import RequestContext

logger = logging.getLogger(__name__)
GROUP = "G24"

_RULES_RELOAD_INTERVAL_S = 60  # Reload rules every 60 seconds


class G24AdaptiveBypass:
    """
    Reads adaptive_bypass_rules.yaml and skips G-groups for matching requests.
    Rules are hot-reloaded from config file on a timer.
    """

    def __init__(self) -> None:
        self._rules: List[Dict[str, Any]] = []
        self._last_loaded: float = 0.0
        self._rules_path: Optional[str] = None

    def _load_rules(self, config: Dict[str, Any]) -> None:
        """Load bypass rules from YAML config file."""
        import time

        now = time.time()
        if now - self._last_loaded < _RULES_RELOAD_INTERVAL_S and self._rules:
            return

        # Determine rules file path
        g24_cfg = config.get("groups", {}).get("G24_adaptive_bypass", {})
        # Captured BEFORE local-path resolution mangles `rules_path` below (e.g. an
        # "/app/" container prefix) — GCS is a flat namespace, so the GCS fallback must use
        # the operator-configured value as-written, not a local filesystem artifact.
        configured_rules_file = g24_cfg.get("rules_file", "config/adaptive_bypass_rules.yaml")
        rules_path = configured_rules_file

        # Resolve relative to project root or absolute
        if not os.path.isabs(rules_path):
            # In container: WORKDIR=/app, so config/ is at /app/config/
            # Locally: relative to cwd
            if not os.path.exists(rules_path):
                # Try common container paths
                for prefix in ["/app/", ""]:
                    candidate = os.path.join(prefix, rules_path)
                    if os.path.exists(candidate):
                        rules_path = candidate
                        break

        if not os.path.exists(rules_path):
            # GCS fallback: in GCP the rules file is not in the container image
            # (built from src/proxy/ context). Download from CONFIG_GCS_BUCKET if set.
            gcs_bucket = os.getenv("CONFIG_GCS_BUCKET", "")
            if gcs_bucket:
                try:
                    from google.cloud import storage as _gcs  # type: ignore
                    # Same object signal_miner.write_rules() uploads to when a custom
                    # rules_file is configured — both sides must derive the blob name from
                    # the SAME configured value, or a custom path silently desyncs them.
                    blob_name = configured_rules_file
                    content = _gcs.Client().bucket(gcs_bucket).blob(blob_name).download_as_text()
                    data = yaml.safe_load(content) or {}
                    adaptive_bypass = data.get("adaptive_bypass", {})
                    if adaptive_bypass.get("enabled", True):
                        self._rules = adaptive_bypass.get("rules", [])
                    else:
                        self._rules = []
                    self._last_loaded = now
                    logger.info(
                        "G24: Loaded %d bypass rules from GCS gs://%s/%s",
                        len(self._rules), gcs_bucket, blob_name,
                    )
                    return
                except Exception as exc:
                    logger.warning(
                        "G24: GCS rules fetch failed: %s — no bypass rules applied", exc
                    )
            # No rules file and no GCS — disable gracefully
            self._rules = []
            self._last_loaded = now
            return

        try:
            with open(rules_path, "r") as f:
                data = yaml.safe_load(f) or {}

            adaptive_bypass = data.get("adaptive_bypass", {})
            if not adaptive_bypass.get("enabled", True):
                self._rules = []
                self._last_loaded = now
                return

            self._rules = adaptive_bypass.get("rules", [])
            self._rules_path = rules_path
            self._last_loaded = now
            logger.debug("G24: Loaded %d bypass rules from %s", len(self._rules), rules_path)
        except Exception as exc:
            logger.warning("G24: Failed to load rules from %s: %s", rules_path, exc)
            self._last_loaded = now

    async def process_request(self, ctx: RequestContext) -> RequestContext:
        """Check request against bypass rules and populate skip_groups."""
        cfg = ctx.config.get("groups", {}).get("G24_adaptive_bypass", {})
        if not cfg.get("enabled", True):
            return ctx

        self._load_rules(ctx.config)

        if not self._rules:
            return ctx

        # Ensure skip_groups exists on context
        if not hasattr(ctx, "skip_groups"):
            ctx.skip_groups = []

        matched_rules = []
        for rule in self._rules:
            if not rule.get("enabled", True):
                continue
            if self._matches(ctx, rule):
                group = rule.get("group", "")
                if group and group not in ctx.skip_groups:
                    ctx.skip_groups.append(group)
                    matched_rules.append(rule)

        if matched_rules:
            reasons = [r.get("reason", "adaptive bypass") for r in matched_rules]
            groups_skipped = [r.get("group") for r in matched_rules]
            logger.info(
                "[%s] G24: Bypassing %s — %s",
                ctx.request_id,
                ", ".join(groups_skipped),
                "; ".join(reasons),
            )
            # Record in savings for observability
            ctx.savings.add_step(
                group=GROUP,
                description=f"Adaptive bypass: skipping {', '.join(groups_skipped)}",
                tokens_before=ctx.current_token_count,
                tokens_after=ctx.current_token_count,
            )

        return ctx

    async def reevaluate_post_routing(self, ctx: RequestContext) -> RequestContext:
        """Re-run rule matching after G06 routing has set `ctx.routed_model`.

        The main `process_request` pass runs BEFORE G06 (Stage 1b), so a rule whose
        `models` condition is scoped to the POST-routing model — e.g. a learned rule from
        the F1 signal miner, keyed on `usage_events.routed_model` — can never match at that
        point for a tenant using G06 tiered/cascade routing: `ctx.model` and
        `ctx.routed_model` are still identical (both the originally-requested label) until
        G06 reassigns `routed_model`. This narrower second pass re-checks only rules not
        already matched, now that routing is final and before any Stage 3/4 group (all of
        which run after G06) has executed — so a late match still fully takes effect.
        """
        cfg = ctx.config.get("groups", {}).get("G24_adaptive_bypass", {})
        if not cfg.get("enabled", True):
            return ctx

        self._load_rules(ctx.config)
        if not self._rules:
            return ctx

        if not hasattr(ctx, "skip_groups"):
            ctx.skip_groups = []

        newly_matched = []
        for rule in self._rules:
            if not rule.get("enabled", True):
                continue
            group = rule.get("group", "")
            if not group or group in ctx.skip_groups:
                continue  # already matched in the pre-routing pass
            if self._matches(ctx, rule):
                ctx.skip_groups.append(group)
                newly_matched.append(rule)

        if newly_matched:
            reasons = [r.get("reason", "adaptive bypass") for r in newly_matched]
            groups_skipped = [r.get("group") for r in newly_matched]
            logger.info(
                "[%s] G24: Bypassing %s post-routing — %s",
                ctx.request_id,
                ", ".join(groups_skipped),
                "; ".join(reasons),
            )
            ctx.savings.add_step(
                group=GROUP,
                description=f"Adaptive bypass (post-routing): skipping {', '.join(groups_skipped)}",
                tokens_before=ctx.current_token_count,
                tokens_after=ctx.current_token_count,
            )

        return ctx

    def _matches(self, ctx: RequestContext, rule: Dict[str, Any]) -> bool:
        """Check if a request matches a bypass rule's conditions."""
        conditions = rule.get("conditions", {})
        if not conditions:
            return True  # No conditions = always match

        # Check min_prompt_tokens
        min_tokens = conditions.get("min_prompt_tokens", 0)
        if min_tokens > 0 and ctx.current_token_count < min_tokens:
            return False

        # Check max_prompt_tokens (if specified)
        max_tokens = conditions.get("max_prompt_tokens", 0)
        if max_tokens > 0 and ctx.current_token_count > max_tokens:
            return False

        # Check model restriction
        models = conditions.get("models", [])
        if models and ctx.model not in models and ctx.routed_model not in models:
            return False

        # Check tenant restriction
        tenants = conditions.get("tenants", [])
        if tenants and ctx.tenant_id not in tenants:
            return False

        # Check dataset/feature tag (stored in params by ROI harness)
        datasets = conditions.get("datasets", [])
        if datasets:
            request_dataset = ctx.params.get("x_dataset", ctx.params.get("dataset_id", ""))
            if request_dataset and request_dataset not in datasets:
                return False

        return True
