"""
Guard: the proxy + test dependency lockfiles stay compiled, complete and consistent.

src/proxy/requirements.txt and tests/requirements-test.txt are pip-compile OUTPUT
(generated from the *.in files by scripts/compile-requirements.sh) — CI and the
Docker image install the pinned resolve, which is what makes contributor CI
deterministic. This test fails when:

  * someone edits a compiled file by hand back into ">=" floors,
  * a direct dependency added to a .in file is missing from the compiled pins
    (i.e. the compile step was skipped),
  * the two lockfiles pin a shared package at different versions (CI installs
    both into ONE environment), or
  * a regeneration reintroduces the deliberately-excluded platform packages:
    torch (the Dockerfile preinstalls the CPU build; a PyPI pin would drag the
    ~2.5 GB CUDA wheel into the image), nvidia-*/triton (CUDA runtime), or
    uvloop (Linux-only; an unconditional pin breaks Windows dev installs).
    Dependabot regenerates lockfiles from the header command, so this is the
    backstop if that command ever loses the exclusions.
"""
import re
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent.parent

PAIRS = [
    ("src/proxy/requirements.in", "src/proxy/requirements.txt"),
    ("tests/requirements-test.in", "tests/requirements-test.txt"),
]

# Never allowed as pins in the proxy lockfile (canonical names / prefixes).
FORBIDDEN_PIN_PREFIXES = ("torch", "nvidia-", "triton", "uvloop")


def _canonical(name: str) -> str:
    """PEP 503 canonical form: case-insensitive, runs of -_. collapse to -."""
    return re.sub(r"[-_.]+", "-", name).strip().lower()


def _requirement_lines(rel: str):
    """Non-comment requirement lines of a requirements file."""
    text = (REPO_ROOT / rel).read_text(encoding="utf-8")
    for line in text.splitlines():
        line = line.split(" #")[0].strip()
        if not line or line.startswith(("#", "-")):
            continue
        yield line


def _name_of(line: str) -> str:
    """`uvicorn[standard]>=0.30.0` -> `uvicorn` (canonical)."""
    return _canonical(re.split(r"[<>=!~;\[]", line, 1)[0])


def _pins(rel: str) -> dict:
    """{canonical-name: version} for every `pkg==version` line in a lockfile."""
    pins = {}
    for line in _requirement_lines(rel):
        m = re.match(r"^([A-Za-z0-9][A-Za-z0-9._\[\],-]*?)==(\S+)$", line)
        if m:
            pins[_name_of(m.group(1))] = m.group(2)
    return pins


def test_compiled_files_carry_the_pip_compile_header():
    """Hand-reverting a lockfile to floors must fail loudly."""
    for _, txt in PAIRS:
        head = (REPO_ROOT / txt).read_text(encoding="utf-8")[:400]
        assert "autogenerated by pip-compile" in head, (
            f"{txt} is not pip-compile output — regenerate it with "
            "scripts/compile-requirements.sh instead of editing it by hand"
        )


def test_every_compiled_line_is_an_exact_pin():
    for _, txt in PAIRS:
        loose = [l for l in _requirement_lines(txt) if "==" not in l]
        assert not loose, (
            f"{txt} contains non-pinned requirement lines {loose} — it must be a "
            "full `pkg==version` resolve (scripts/compile-requirements.sh)"
        )


def test_every_direct_dependency_is_pinned():
    """A dep added to a .in file without regenerating the lockfile never installs."""
    for infile, txt in PAIRS:
        pinned = set(_pins(txt))
        missing = [
            _name_of(l) for l in _requirement_lines(infile)
            if _name_of(l) not in pinned
        ]
        assert not missing, (
            f"direct dependencies {missing} from {infile} are missing from {txt} — "
            "run scripts/compile-requirements.sh to regenerate the pins"
        )


def test_platform_sensitive_packages_stay_unpinned():
    """torch/CUDA/uvloop pins must never land in the proxy lockfile (image bloat /
    Windows breakage) — see the exclusion note in scripts/compile-requirements.sh."""
    offenders = [
        name for name in _pins("src/proxy/requirements.txt")
        if name.startswith(FORBIDDEN_PIN_PREFIXES)
    ]
    assert not offenders, (
        f"forbidden platform-sensitive pins {offenders} in src/proxy/requirements.txt — "
        "regenerate with scripts/compile-requirements.sh (which excludes them)"
    )


def test_shared_pins_agree_across_lockfiles():
    """CI installs both lockfiles into one environment — shared packages must
    resolve identically (the tests compile is constrained by the proxy pins)."""
    proxy = _pins("src/proxy/requirements.txt")
    tests = _pins("tests/requirements-test.txt")
    conflicts = {
        name: (proxy[name], tests[name])
        for name in proxy.keys() & tests.keys()
        if proxy[name] != tests[name]
    }
    assert not conflicts, (
        f"lockfiles disagree on shared pins {conflicts} — regenerate BOTH with "
        "scripts/compile-requirements.sh (the tests compile takes the proxy pins "
        "as constraints)"
    )
