"""
Guard: the proxy + test dependency lockfiles stay compiled, complete and consistent.

src/proxy/requirements.txt and tests/requirements-test.txt are pip-compile OUTPUT
(generated from the *.in files by scripts/compile-requirements.sh) — CI and the
Docker image install the pinned resolve, which is what makes contributor CI
deterministic. This test fails when:

  * someone edits a compiled file by hand back into ">=" floors,
  * a direct dependency added to a .in file is missing from the compiled pins
    (i.e. the compile step was skipped),
  * the two lockfiles pin a shared package at different versions (CI installs
    both into ONE environment), or
  * a regeneration reintroduces the deliberately-excluded platform packages:
    torch (the Dockerfile preinstalls the CPU build; a PyPI pin would drag the
    ~2.5 GB CUDA wheel into the image), nvidia-*/cuda-*/triton (CUDA runtime), or
    uvloop (Linux-only; an unconditional pin breaks Windows dev installs).
    Dependabot regenerates lockfiles from the header command, so this is the
    backstop if that command ever loses the exclusions.
"""
import re
from pathlib import Path

import pytest
from packaging.requirements import Requirement
from packaging.version import Version

REPO_ROOT = Path(__file__).parent.parent.parent

PAIRS = [
    ("src/proxy/requirements.in", "src/proxy/requirements.txt"),
    ("tests/requirements-test.in", "tests/requirements-test.txt"),
]

# Never allowed as pins in the proxy lockfile (canonical names / prefixes). cuda-*: newer torch
# reaches the CUDA runtime through cuda-toolkit and cuda-bindings, not nvidia-* directly, and the
# proxy image shipped 1.7 GB of it beside its CPU torch.
FORBIDDEN_PIN_PREFIXES = ("torch", "nvidia-", "cuda-", "triton", "uvloop")


def _canonical(name: str) -> str:
    """PEP 503 canonical form: case-insensitive, runs of -_. collapse to -."""
    return re.sub(r"[-_.]+", "-", name).strip().lower()


def _requirement_lines(rel: str):
    """Non-comment requirement lines of a requirements file."""
    text = (REPO_ROOT / rel).read_text(encoding="utf-8")
    for line in text.splitlines():
        line = line.split(" #")[0].strip()
        if not line or line.startswith(("#", "-")):
            continue
        yield line


def _name_of(line: str) -> str:
    """`uvicorn[standard]>=0.30.0` -> `uvicorn` (canonical)."""
    return _canonical(re.split(r"[<>=!~;\[]", line, 1)[0])


def _pins(rel: str) -> dict:
    """{canonical-name: version} for every `pkg==version` line in a lockfile."""
    pins = {}
    for line in _requirement_lines(rel):
        m = re.match(r"^([A-Za-z0-9][A-Za-z0-9._\[\],-]*?)==(\S+)$", line)
        if m:
            pins[_name_of(m.group(1))] = m.group(2)
    return pins


def _left_out(rel: str) -> set:
    """What pip-compile left out of a lockfile (--unsafe-package): the list that closes it."""
    text = (REPO_ROOT / rel).read_text(encoding="utf-8")
    footer = text.partition("considered to be unsafe in a requirements file:")[2]
    return {_canonical(line.lstrip("# ")) for line in footer.splitlines() if line.startswith("# ")}


def test_compiled_files_carry_the_pip_compile_header():
    """Hand-reverting a lockfile to floors must fail loudly."""
    for _, txt in PAIRS:
        head = (REPO_ROOT / txt).read_text(encoding="utf-8")[:400]
        assert "autogenerated by pip-compile" in head, (
            f"{txt} is not pip-compile output — regenerate it with "
            "scripts/compile-requirements.sh instead of editing it by hand"
        )


def test_every_compiled_line_is_an_exact_pin():
    for _, txt in PAIRS:
        loose = [l for l in _requirement_lines(txt) if "==" not in l]
        assert not loose, (
            f"{txt} contains non-pinned requirement lines {loose} — it must be a "
            "full `pkg==version` resolve (scripts/compile-requirements.sh)"
        )


def test_every_direct_dependency_is_pinned():
    """A dep added to a .in file without regenerating the lockfile never installs."""
    for infile, txt in PAIRS:
        pinned = set(_pins(txt)) | _left_out(txt)     # torch: its Dockerfile installs it
        missing = [
            _name_of(l) for l in _requirement_lines(infile)
            if _name_of(l) not in pinned
        ]
        assert not missing, (
            f"direct dependencies {missing} from {infile} are missing from {txt} — "
            "run scripts/compile-requirements.sh to regenerate the pins"
        )


def test_every_pin_meets_its_floor():
    """pip installs the pin, never the floor: a floor raised past a vulnerable release protects
    nothing while the lockfile still pins that release."""
    for infile, txt in PAIRS:
        pins = _pins(txt)
        outside = {}
        for line in _requirement_lines(infile):
            req = Requirement(line)
            pinned = pins.get(_canonical(req.name))
            if pinned and not req.specifier.contains(Version(pinned), prereleases=True):
                outside[req.name] = f"pinned {pinned}, {infile} says {req.specifier}"
        assert not outside, (
            f"{txt} pins versions its {infile} rules out: {outside} — "
            "regenerate with scripts/compile-requirements.sh"
        )


def test_platform_sensitive_packages_stay_unpinned():
    """torch/CUDA/uvloop pins must never land in the proxy lockfile (image bloat /
    Windows breakage) — see the exclusion note in scripts/compile-requirements.sh."""
    offenders = [
        name for name in _pins("src/proxy/requirements.txt")
        if name.startswith(FORBIDDEN_PIN_PREFIXES)
    ]
    assert not offenders, (
        f"forbidden platform-sensitive pins {offenders} in src/proxy/requirements.txt — "
        "regenerate with scripts/compile-requirements.sh (which excludes them)"
    )


def test_shared_pins_agree_across_lockfiles():
    """CI installs both lockfiles into one environment — shared packages must
    resolve identically (the tests compile is constrained by the proxy pins)."""
    proxy = _pins("src/proxy/requirements.txt")
    tests = _pins("tests/requirements-test.txt")
    conflicts = {
        name: (proxy[name], tests[name])
        for name in proxy.keys() & tests.keys()
        if proxy[name] != tests[name]
    }
    assert not conflicts, (
        f"lockfiles disagree on shared pins {conflicts} — regenerate BOTH with "
        "scripts/compile-requirements.sh (the tests compile takes the proxy pins "
        "as constraints)"
    )


# ── The sidecar and pipeline images ───────────────────────────────────────────
# Each installed open ">=" floors, so every rebuild took whatever was newest that day and no
# past image could be rebuilt. Each now has a requirements.in that the compile script resolves
# into a pinned requirements.txt, as the proxy's is.
SIDECARS = ["src/llmlingua-sidecar", "src/routellm-sidecar", "src/doc-pipeline",
            "src/finetune-pipeline"]


@pytest.mark.parametrize("image", SIDECARS)
def test_each_image_has_a_source_list_the_compile_script_resolves(image):
    assert list(_requirement_lines(f"{image}/requirements.in")), f"{image}/requirements.in"
    script = (REPO_ROOT / "scripts" / "compile-requirements.sh").read_text(encoding="utf-8")
    loop = re.search(r"for dir in ([^;]+); do", script)
    assert loop and Path(image).name in loop.group(1).split()


def test_the_compile_leaves_the_platform_packages_out_of_every_image_lockfile():
    # The proxy's compile and the loop's: the lockfile guards above see a lost flag only after
    # the next compile has pinned the CUDA build.
    script = (REPO_ROOT / "scripts" / "compile-requirements.sh").read_text(encoding="utf-8")
    flags = "--unsafe-package torch --unsafe-package triton --unsafe-package uvloop"
    assert script.count(flags) == 2


@pytest.mark.parametrize("image", SIDECARS)
def test_each_image_installs_pinned_versions(image):
    txt = f"{image}/requirements.txt"
    assert "autogenerated by pip-compile" in (REPO_ROOT / txt).read_text(encoding="utf-8")[:400]
    assert all("==" in line for line in _requirement_lines(txt))
    pinned = set(_pins(txt))
    assert all(_name_of(line) in pinned | _left_out(txt)          # torch: its Dockerfile installs it
               for line in _requirement_lines(f"{image}/requirements.in"))
    assert not [name for name in pinned if name.startswith(FORBIDDEN_PIN_PREFIXES)]


@pytest.mark.parametrize("image", ["src/proxy", *SIDECARS])
def test_an_image_whose_pins_need_torch_installs_the_cpu_torch_they_were_resolved_against(image):
    # torch is left out of requirements.txt (a PyPI pin would pull the CUDA build), so an image
    # whose pins need it installs it first, from PyTorch's CPU index, pinned. requirements.in
    # names the same torch, so the compile resolves the pins against the torch the image runs:
    # resolved against a newer one, they could need it, and pip would fetch it from PyPI, CUDA
    # build and all.
    dockerfile = (REPO_ROOT / image / "Dockerfile").read_text(encoding="utf-8")
    installs = re.findall(r"^RUN pip install --no-cache-dir torch(\S*) --index-url "
                          r"https://download\.pytorch\.org/whl/cpu$", dockerfile, re.M)
    named = [line[len("torch"):] for line in _requirement_lines(f"{image}/requirements.in")
             if _name_of(line) == "torch"]
    if "torch" not in _left_out(f"{image}/requirements.txt"):
        assert not installs and not named, (installs, named)     # nothing in this image needs it
        return
    assert len(installs) == 1 and re.fullmatch(r"==\d+\.\d+\.\d+", installs[0]), installs
    assert named == installs, (named, installs)
    assert (dockerfile.index("RUN pip install --no-cache-dir torch")
            < dockerfile.index("RUN pip install --no-cache-dir -r requirements.txt"))
